// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title MemeToken
 * @dev Standard ERC-20 token template for meme coins
 * Generated by AI Meme Coin Generator
 */
contract MemeToken is ERC20, ERC20Burnable, Ownable {
    
    // Maximum supply cap
    uint256 public immutable MAX_SUPPLY;
    
    // Token metadata
    string private _tokenDescription;
    string private _website;
    string private _logoURI;
    
    // Events
    event MetadataUpdated(string description, string website, string logoURI);
    
    /**
     * @dev Constructor to initialize the meme token
     * @param name_ Token name
     * @param symbol_ Token symbol
     * @param maxSupply_ Maximum token supply (without decimals)
     * @param initialOwner Address that will receive initial supply and own the contract
     */
    constructor(
        string memory name_,
        string memory symbol_,
        uint256 maxSupply_,
        address initialOwner
    ) ERC20(name_, symbol_) Ownable(initialOwner) {
        require(initialOwner != address(0), "Invalid owner address");
        require(maxSupply_ > 0, "Max supply must be greater than 0");
        
        MAX_SUPPLY = maxSupply_ * 10**decimals();
        
        // Mint initial supply to owner
        _mint(initialOwner, MAX_SUPPLY);
    }
    
    /**
     * @dev Update token metadata (description, website, logo)
     * Only callable by owner
     */
    function updateMetadata(
        string memory description_,
        string memory website_,
        string memory logoURI_
    ) external onlyOwner {
        _tokenDescription = description_;
        _website = website_;
        _logoURI = logoURI_;
        
        emit MetadataUpdated(description_, website_, logoURI_);
    }
    
    /**
     * @dev Get token metadata
     */
    function getMetadata() external view returns (
        string memory description,
        string memory website,
        string memory logoURI
    ) {
        return (_tokenDescription, _website, _logoURI);
    }
    
    /**
     * @dev Get comprehensive token information
     */
    function tokenInfo() external view returns (
        string memory tokenName,
        string memory tokenSymbol,
        uint256 totalSupply_,
        uint256 maxSupply_,
        uint8 tokenDecimals
    ) {
        return (
            name(),
            symbol(),
            totalSupply(),
            MAX_SUPPLY,
            decimals()
        );
    }
    
    /**
     * @dev Allows owner to airdrop tokens to multiple addresses
     * Useful for community rewards and marketing
     */
    function airdrop(
        address[] calldata recipients,
        uint256[] calldata amounts
    ) external onlyOwner {
        require(recipients.length == amounts.length, "Arrays length mismatch");
        require(recipients.length <= 200, "Too many recipients");
        
        for (uint256 i = 0; i < recipients.length; i++) {
            require(recipients[i] != address(0), "Invalid recipient");
            _transfer(msg.sender, recipients[i], amounts[i]);
        }
    }
    
    /**
     * @dev Emergency function to recover accidentally sent ERC20 tokens
     * Cannot recover the meme token itself
     */
    function recoverERC20(
        address tokenAddress,
        uint256 tokenAmount
    ) external onlyOwner {
        require(tokenAddress != address(this), "Cannot recover meme token");
        IERC20(tokenAddress).transfer(owner(), tokenAmount);
    }
}

